refactor: use hashicorp go-plugin
goto/siren pull request #25
Opened 2023-09-11 13:48 UTC by mabdh

2023-09-12 12:03 UTC, ishanarya0 requested changes

2023-09-18 04:27 UTC, mabdh commented on plugins/providers/cortex/v1/service.go
> +		return errors.New("Cortex webhook base api string in config cannot be empty")
@ishanarya0 it is fine for this ishan, the `Cortex` here is a brand name and not a generic english word.

2023-09-18 04:27 UTC, mabdh commented on plugins/providers/cortex/.goreleaser.yml
> +project_name: sirne-cortex
nice catch, sure will change it

2023-09-18 09:42 UTC, ishanarya0 approved these changes

2023-09-18 12:15 UTC, merged